---

username: "admin"
password: "admin"
server_url: "https://foreman.localdomain"
organization: "Netways"

foreman_repositories_version: "3.12"
foreman_repositories_katello_version: "4.14"

foreman_puppet_repositories_version: 8
foreman_installer_scenario: katello
foreman_installer_package: foreman-installer-katello
foreman_installer_options:
  - '--foreman-proxy-tftp=true'
  - '--foreman-proxy-tftp-servername 10.0.0.2'
  - '--foreman-proxy-dns=true'
  - '--foreman-proxy-dns-interface=enp1s0'
  - '--foreman-proxy-dns-zone=localdomain'
  - '--foreman-proxy-dns-reverse=0.10.in-addr.arpa'
  - '--foreman-proxy-dns-forwarders=8.8.8.8'
  - '--foreman-proxy-dns-forwarders=8.8.4.4'
  - '--foreman-proxy-dhcp=true'
  - '--foreman-proxy-dhcp-interface=enp1s0'
  - '--foreman-proxy-dhcp-gateway=10.0.0.1'
  - '--foreman-proxy-dhcp-range="10.0.0.100 10.0.0.200"'
  - '--foreman-proxy-dhcp-nameservers="10.0.0.2"'
  - '--foreman-initial-organization "Netways"'
  - '--foreman-initial-admin-password admin'
  - '--tuning "development"'
  - '--enable-foreman-compute-libvirt'
    # foreman_proxy_certs_generate_fqdn: "{{ ansible_fqdn }}"

