---
- name: Install Foreman Server with Katello
  hosts: foreman-server
  become: true
  gather_facts: true
 
    #  pre_tasks:
    #    - name: Install Foreman SELinux Package
    #      ansible.builtin.dnf:
    #        name: foreman-selinux
    #        state: present
  tasks:
    - name: "Setup Dns-Proxy for Domain"
      theforeman.foreman.domain:
        name: "localdomain"
        description: "localdomain"
        organizations:
          - "Netways"
        server_url: "https://foreman.localdomain"
        username: "admin"
        password: "admin"
        dns_proxy: "foreman.localdomain"
        state: present

    - name: "Create Subnet foreman"
      theforeman.foreman.subnet:
        name: "foreman"
        network_type: "IPv4"
        network: "10.0.0.0"
        cidr: "16"
        mask: "255.255.0.0"
        gateway: "10.0.0.1"
        dns_primary: "10.0.0.2"
        ipam: "DHCP"
        boot_mode: "DHCP"
        from_ip: "10.0.0.100"
        to_ip: "10.0.0.200"
        dhcp_proxy: "foreman.localdomain"
        tftp_proxy: "foreman.localdomain"
        dns_proxy: "foreman.localdomain"
        domains:
          - "localdomain"
        server_url: "https://foreman.localdomain"
        username: "admin"
        password: "admin"
        state: present

    - name: "Copy private key SSH-Key to foreman user"
      ansible.builtin.copy:
        src: "files/id_rsa"
        dest: "/usr/share/foreman/.ssh/id_rsa"

    - name: "Add host root@foreman.localdomain to known_hosts"
      ansible.builtin.known_hosts:
        path: "/usr/share/foreman/.ssh/known_hosts"
        name: "host.localdomain"
        hash_host: false
        key: "{{ lookup('pipe', 'ssh-keyscan -H -t rsa host.localdomain') | trim }}"

    - name: "Add foreman-key to authorized keys for root user"
      ansible.posix.authorized_key:
        user: root
        state: present
        key: "{{ lookup('file', 'files/id_rsa.pub') }}"
      delegate_to: localhost

    - name: "Create libvirt compute resource"
      theforeman.foreman.compute_resource:
        name: "libvirt"
        organizations:
          - "Netways"
        provider: "libvirt"
        provider_params:
          url: "qemu+ssh://root@host.localdomain/system"
          display_type: "vnc"
          set_console_password: "false"
        server_url: "https://foreman.localdomain"
        username: "admin"
        password: "admin"
        state: present
    
    - name: "Create Directory /var/www/html/pub/ubuntu"
      ansible.builtin.file:
        path: "/var/www/html/pub/ubuntu"
        state: directory
        mode: "0755"

    - name: "Download Ubuntu 24.04 LTS iso"
      ansible.builtin.get_url:
        url: "https://releases.ubuntu.com/noble/ubuntu-24.04.1-live-server-amd64.iso" 
        dest: "/var/www/html/pub/ubuntu/24.04.1-amd64.iso"
        mode: "0755"
    
    - name: "Mount Ubuntu Iso"
      ansible.posix.mount:
        src: "/var/www/html/pub/ubuntu/24.04.1-amd64.iso"
        path: "/var/www/html/pub/ubuntu/24.04.1-amd64"
        fstype: "iso9660"
        opts: ro,noauto
        boot: false
        state: mounted

    - name: "Create Symlink for ISO"
      ansible.builtin.file:
        src: "/var/www/html/pub/ubuntu/24.04.1-amd64.iso"
        dest: "/var/www/html/pub/ubuntu/24.04.1-x86_64.iso"
        state: link
  
    - name: "Create Symlink for Directory"
      ansible.builtin.file:
        src: "/var/www/html/pub/ubuntu/24.04.1-amd64"
        dest: "/var/www/html/pub/ubuntu/24.04.1-x86_64"
        state: link

    - name: "Create Operating System Architecture x86_64"
      theforeman.foreman.architecture:
        name: "x86_64"
        server_url: "https://foreman.localdomain"
        username: "admin"
        password: "admin"
        state: "present"

    - name: "Create Operating System Ubuntu 24.04.1"
      theforeman.foreman.operatingsystem:
        username: "admin"
        password: "admin"
        server_url: "https://foreman.localdomain"
        architectures: 
          - "x86_64"
        name: "Ubuntu"
        release_name: "noble"
        family: "Debian"
        major: "24.04"
        minor: "1"
        description: "Ubuntu Noble Numbat Test"
        password_hash: "SHA256"
        ptables:
          - "Preseed default autoinstall"
        provisioning_templates: 
          - "Preseed default finish"
          - "Linux host_init_config default"
          - "Preseed default iPXE"
          - "Preseed default PXEGrub2"
          - "Preseed default PXELinux Autoinstall"
          - "Preseed Autoinstall cloud-init user data"
        state: "present"

    - name: "Create Installation Medium for Ubuntu 24.04.1"
      theforeman.foreman.installation_medium:
        name: "Ubuntu Autoinstall 2"
        operatingsystems: 
          - "Ubuntu Noble Numbat Test"
        path: "http://foreman.localdomain/pub/ubuntu/$major.$minor-$arch"
        os_family: "Debian"
        organizations:
          - "Netways"
        server_url: "https://foreman.localdomain"
        username: "admin"
        password: "admin"
        state: "present"

    - name: "Create Association for Finish"
      theforeman.foreman.os_default_template:
        username: "admin"
        password: "admin"
        server_url: "https://foreman.localdomain"
        operatingsystem: "Ubuntu Noble Numbat Test"
        template_kind: "finish"
        provisioning_template: "Preseed default finish"
        state: "present"

    - name: "Create Association for Host initial configuration template"
      theforeman.foreman.os_default_template:
        username: "admin"
        password: "admin"
        server_url: "https://foreman.localdomain"
        operatingsystem: "Ubuntu Noble Numbat Test"
        template_kind: "host_init_config"
        provisioning_template: "Linux host_init_config default"
        state: "present"

    - name: "Create Association for iPXE template"
      theforeman.foreman.os_default_template:
        username: "admin"
        password: "admin"
        server_url: "https://foreman.localdomain"
        operatingsystem: "Ubuntu Noble Numbat Test"
        template_kind: "iPXE"
        provisioning_template: "Preseed default iPXE"
        state: "present"

    - name: "Create Association for PXEGrub2 template"
      theforeman.foreman.os_default_template:
        username: "admin"
        password: "admin"
        server_url: "https://foreman.localdomain"
        operatingsystem: "Ubuntu Noble Numbat Test"
        template_kind: "PXEGrub2"
        provisioning_template: "Preseed default PXEGrub2"
        state: "present"
          
    - name: "Create Association for PXELinux template"
      theforeman.foreman.os_default_template:
        username: "admin"
        password: "admin"
        server_url: "https://foreman.localdomain"
        operatingsystem: "Ubuntu Noble Numbat Test"
        template_kind: "PXELinux"
        provisioning_template: "Preseed default PXELinux Autoinstall"
        state: "present"

    - name: "Create Association for User data template"
      theforeman.foreman.os_default_template:
        username: "admin"
        password: "admin"
        server_url: "https://foreman.localdomain"
        operatingsystem: "Ubuntu Noble Numbat Test"
        template_kind: "user_data"
        provisioning_template: "Preseed Autoinstall cloud-init user data"
        state: "present"

          #    - name: "Update Compute Profile 1-Small"
          #      theforeman.foreman.compute_profile:
          #        name: "1-Small"
          #        username: "admin"
          #        password: "admin"
          #        server_url: "https://foreman.localdomain"
          #        compute_attributes:
          #          - compute_resource: "libvirt"
          #            vm_attrs:
          #              nics_attributes:
          #                0:
          #                  type: "network"
          #                  network: "foreman"
          #                  bridge: "virbr1"
          #                  interface: "virtio"
                    #- name: "Create Host"
                    #  theforeman.foreman.host:
                    #    username: "admin"
                    #    password: "admin"
                    #    server_url: "https://foreman.localdomain"
                    #    organization: "Netways"
                    #    location: "Default Location"
                    #    name: "test-ubuntu.localdomain"
                    #    build: true
                    #    architecture: "x86_64"
                    #    compute_resource: "libvirt"
                    #    operatingsystem: "Ubuntu Noble Numbat Test"
                    #    provision_method: "build"
                    #    content_source: "foreman.localdomain"
                    #    ptable: "Preseed default autoinstall" 
                    #    pxe_loader: "PXELinux BIOS"
                    #    root_pass: "12345abc"
                    #    compute_profile: "1-Small"
                    #    domain: "localdomain"
                    #    compute_attributes:
                    #      cpus: "4"
                    #      memory: "4096"
                    #      type: "qcow2"
                    #      start: true
                    #    medium: "Ubuntu Autoinstall 2" 
                    #    state: present

    - name: "Create Test Host"
      theforeman.foreman.host:
        username: "admin"
        password: "admin"
        server_url: "https://foreman.localdomain"
        location: "Default Location"
        organization: "Netways"
        name: "test-ubuntu.localdomain"
        build: true
        architecture: "x86_64"
        content_source: "foreman.localdomain"
        compute_resource: "libvirt"
        provision_method: "build"
        operatingsystem: "Ubuntu Noble Numbat Test"
        ptable: "Preseed default autoinstall" 
        pxe_loader: "PXELinux BIOS"
        root_pass: "12345abc"
        compute_profile: "1-Small"
        domain: "localdomain"
        compute_attributes:
          cpus: "4"
          memory: "4294967296"
          start: "1"
            #volumes_attributes: 
            #  - pool_name: "default"
            #    capacity: "10G"
            #    allocation: "0G"
            #    format_type: "qcow2" 
        medium: "Ubuntu Autoinstall 2" 
        interfaces_attributes:
          - type: "interface"
            compute_attributes:
              type: "network"
              network: "foreman"
              model: "virtio"
        state: present
        subnet: "foreman"
    
  roles:
    - theforeman.operations.foreman_repositories 
    - theforeman.operations.puppet_repositories
    - theforeman.operations.installer
