---
- name: Install Foreman Server with Katello
  hosts: foremanserver
  become: true
  gather_facts: true
  roles:
    - theforeman.operations.foreman_repositories
    - theforeman.operations.puppet_repositories
    - theforeman.operations.installer

  tasks:
    - name: "Setup DNS-Proxy for Domain"
      theforeman.foreman.domain:
        name: "localdomain"
        description: "localdomain"
        organizations:
          - "{{ organization }}"
        server_url: "{{ server_url }}"
        username: "{{ username }}"
        password: "{{ password }}"
        dns_proxy: "foreman.localdomain"
        state: present

    - name: "Create Subnet foreman"
      theforeman.foreman.subnet:
        name: "foreman"
        network_type: "IPv4"
        network: "10.0.0.0"
        cidr: "16"
        mask: "255.255.0.0"
        gateway: "10.0.0.1"
        dns_primary: "10.0.0.2"
        ipam: "DHCP"
        boot_mode: "DHCP"
        from_ip: "10.0.0.100"
        to_ip: "10.0.0.200"
        dhcp_proxy: "foreman.localdomain"
        tftp_proxy: "foreman.localdomain"
        dns_proxy: "foreman.localdomain"
        domains:
          - "localdomain"
        server_url: "{{ server_url }}"
        username: "{{ username }}"
        password: "{{ password }}"
        state: present

    - name: "Copy private key SSH-Key to foreman user"
      ansible.builtin.copy:
        src: "files/id_rsa"
        dest: "/usr/share/foreman/.ssh/id_rsa"
        mode: "0600"
        owner: foreman
        group: foreman

    - name: "Add host root@foreman.localdomain to known_hosts"
      ansible.builtin.known_hosts:
        path: "/usr/share/foreman/.ssh/known_hosts"
        name: "host.localdomain"
        hash_host: false
        key: "{{ lookup('pipe', 'ssh-keyscan -H -t rsa host.localdomain') | trim }}"

    - name: "Add foreman-key to authorized keys for root user"
      ansible.posix.authorized_key:
        user: root
        state: present
        key: "{{ lookup('file', 'files/id_rsa.pub') }}"
      delegate_to: localhost

    - name: "Create libvirt compute resource"
      theforeman.foreman.compute_resource:
        name: "libvirt"
        organizations:
          - "{{ organization }}"
        provider: "libvirt"
        provider_params:
          url: "qemu+ssh://root@host.localdomain/system"
          display_type: "vnc"
          set_console_password: "false"
        server_url: "{{ server_url }}"
        username: "{{ username }}"
        password: "{{ password }}"
        state: present

    - name: "Create Operating System Architecture x86_64"
      theforeman.foreman.architecture:
        name: "x86_64"
        server_url: "{{ server_url }}"
        username: "{{ username }}"
        password: "{{ password }}"
        state: "present"

    - name: "Copy RedHat Manifest to Foreman Server"
      ansible.builtin.copy:
        src: "files/manifest.zip"
        dest: "/root/manifest.zip"
        mode: "0400"
        owner: "root"
        group: "root"

    - name: "Upload the RedHat Developer Subscription for Individuals"
      theforeman.foreman.subscription_manifest:
        username: "{{ username }}"
        password: "{{ password }}"
        server_url: "{{ server_url }}"
        organization: "{{ organization }}"
        state: present
        manifest_path: "/tmp/manifest.zip"

    - name: "Create Repository Set for RHEL 9"
      theforeman.foreman.repository_set:
        username: "{{ username }}"
        password: "{{ password }}"
        server_url: "{{ server_url }}"
        organization: "{{ organization }}"
        product: "Red Hat Enterprise Linux for x86_64"
        label: "{{ item.label }}"
        repositories: "{{ item.repositories | default(omit) }}"
        state: enabled
      loop:
        - label: "rhel-9-for-x86_64-appstream-kickstart"
          repositories:
            - releasever: "9.5"
        - label: "rhel-9-for-x86_64-appstream-rpms"
          repositories:
            - releasever: "9"
        - label: "rhel-9-for-x86_64-baseos-kickstart"
          repositories:
            - releasever: "9.5"
        - label: "rhel-9-for-x86_64-baseos-rpms"
          repositories:
            - releasever: "9"

    - name: "Sync Repository RHEL 9"
      theforeman.foreman.repository_sync:
        username: "{{ username }}"
        password: "{{ password }}"
        server_url: "{{ server_url }}"
        product: "Red Hat Enterprise Linux for x86_64"
        organization: "{{ organization }}"
      changed_when: false

    - name: "Create Activation Key for RHEL9"
      theforeman.foreman.activation_key:
        username: "{{ username }}"
        password: "{{ password }}"
        server_url: "{{ server_url }}"
        name: "Red Hat Enterprise Linux 9"
        organization: "{{ organization }}"
        lifecycle_environment: "Library"
        content_overrides:
          - label: "rhel-9-for-x86_64-appstream-rpms"
            override: enabled
          - label: "rhel-9-for-x86_64-baseos-rpms"
            override: enabled

    - name: "Create Hostgroup"
      theforeman.foreman.hostgroup:
        username: "{{ username }}"
        password: "{{ password }}"
        server_url: "{{ server_url }}"
        name: "Red Hat Enterprise Linux 9"
        architecture: "x86_64"
        activation_keys: "Red Hat Enterprise Linux 9"
        state: present

    - name: "Update Compute Profile 1-Small"
      theforeman.foreman.compute_profile:
        name: "1-Small"
        username: "{{ username }}"
        password: "{{ password }}"
        server_url: "{{ server_url }}"
        compute_attributes:
          - compute_resource: "libvirt"
            vm_attrs:
              volumes_attributes:
                0:
                  pool_name: default
                  capacity: "10G"
                  allocation: "0G"
                  format_type: "qcow2"
              nics_attributes:
                0:
                  type: "network"
                  network: "foreman"
                  bridge: "virbr1"
                  interface: "virtio"

    - name: "Create Test Host"
      theforeman.foreman.host:
        username: "{{ username }}"
        password: "{{ password }}"
        server_url: "{{ server_url }}"
        location: "Default Location"
        organization: "{{ organization }}"
        name: "test-rhel9.localdomain"
        build: true
        architecture: "x86_64"
        content_source: "foreman.localdomain"
        lifecycle_environment: "Library"
        operatingsystem: "RedHat 9.5"
        content_view: "Default Organization View"
        compute_resource: "libvirt"
        provision_method: "build"
        ptable: "Kickstart default"
        pxe_loader: "PXELinux BIOS"
        root_pass: "{{ root_password }}"
        compute_profile: "1-Small"
        domain: "localdomain"
        kickstart_repository: "Red Hat Enterprise Linux 9 for x86_64 - BaseOS Kickstart 9.5"
        compute_attributes:
          cpus: "4"
          memory: "4294967296"
          start: "1"
        interfaces_attributes:
          - type: "interface"
            compute_attributes:
              type: "network"
              network: "foreman"
              model: "virtio"
        state: present
        hostgroup: "Red Hat Enterprise Linux 9"
        subnet: "foreman"
      changed_when: false
